### ISSUE TITLE
Branch coverage not showing

### ISSUE THREAD

**Issue by craig-landry** [grosser/single_cov#12]
Hi Michael,

I'm trying out single_cov and have it working for line coverage, but cannot get the branch coverage to show, which is what attracted me to the project.  Would you please help me to understand how I can configure that?  It looks like per b70d14e923831ff4b033243c2d3b599db4f5725d it should just work, but I don't see it in the rspec output.  For the purpose of debugging I've thrown together this sample Rails project with rspec with commits separating out the important parts: https://github.com/craig-landry/coverage-project/commits/master

The `Book` model being tested intentionally has lines that are missing coverage and also missed branches.

When running rspec on that project, here's what I see for output:
```
➜  coverage-project git:(master) ✗ ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
```

```
➜  coverage-project git:(master) ✗ rspec
.

Finished in 0.0069 seconds (files took 1.12 seconds to load)
1 example, 0 failures

app/models/book.rb new uncovered lines introduced (2 current vs 0 configured)
Lines missing coverage:
app/models/book.rb:7
app/models/book.rb:9
```

Thanks,
Craig

**Comment by grosser** [comment]
what version of single_cov is it using ? ... check Gemfile.lock

**Comment by grosser** [comment]
nvm ... can see it in the PR :D

**Comment by grosser** [comment]
with:

```
    it "foo" do
      subject.displayable_size
    end
```

it shows:

```
app/models/book.rb new uncovered lines introduced (2 current vs 0 configured)
Lines missing coverage:
app/models/book.rb:9
app/models/book.rb:7:5-7:33
```

I decided to not show duplicate missing coverages since showing the line missing and then each branch missing was kinda annoying to me

**Comment by craig-landry** [comment]
Ah, I see.  Thanks for looking into it and for helping me understand.

**Comment by grosser** [comment]
np :D
