### ISSUE TITLE
Different behavior with ruby >= 2.5

### ISSUE THREAD

**Issue by ddnexus** [grosser/single_cov#19]
Hi @grosser 
single_cov is counting (or not) different lines with different rubies.
Please, take a look at these 2 builds in travis:

- https://travis-ci.org/ddnexus/pagy/jobs/485271245 (passes)
- https://travis-ci.org/ddnexus/pagy/jobs/485271246 (fails)

I could conditionally add the uncovered line and make it work, but maybe you can provide a more consistent behavior through ruby versions?

**Comment by grosser** [comment]
`SingleCov.setup <type>, branches: false`
... but best to just fix the coverage :)

**Comment by ddnexus** [comment]
Thanks! I missed the `branches`!
