### ISSUE TITLE
Allow configuring app folders

### ISSUE THREAD

**Issue by ussu** [grosser/single_cov#27]
Hi @grosser ,

The folders that belong in `app/` are hard-coded
https://github.com/grosser/single_cov/blob/19d5de1de3a33725274291236fcd0b29d4d27660/lib/single_cov.rb#L359

I use the gem with Rails and I'd like to cover code in `app` that is not located in these specific folders :)
(or maybe someone could have a folder in `lib` that have one of these name ? although it seems less likely)
It would be great to at least allow the user to configure this list, or to make a more flexible guess!

What do you think?
Thanks,
Sulidi

**Comment by grosser** [comment]
RAILS_APP_FOLDERS is not frozen, so you can just edit it ... but ideally make a PR to make it officially configurable

**Comment by ussu** [comment]
thanks for the reply :)
