### ISSUE TITLE
System/Integration tests?

### ISSUE THREAD

**Issue by swrobel** [grosser/single_cov#4]
First off, thanks for this gem (and everything else super high quality that you produce - I knew when I saw your name on this, my dreams of a lightweight Simplecov alternative had been answered).

For these types of tests that don't have an obvious file to tie coverage to, what do you propose to do? I think the integration/system subdirectories should just be ignored, but maybe I'm overlooking something. Ex from my output:

`spec/system/dashboard_spec.rb: needs to use SingleCov.covered!`

**Comment by grosser** [comment]
I usually use SingleCov.not_covered!
... alternatively add a feature to ignore these directories

**Comment by swrobel** [comment]
Yeah, actually just discovered `SingleCov.not_covered!` right after I posted this. Thanks for the quick reply!
